### ISSUE TITLE
I can't use: npx node-organic/organic-stack-template

### ISSUE THREAD

**Issue by dimitardanailov** [node-organic/organic-stack-template#2]
I'm using Mac OS X: 10.14 and nodejs version 8.9.4

My issue is: 

<img width="500" alt="issue" src="https://user-images.githubusercontent.com/2182018/46281085-5b195600-c576-11e8-8c41-c261ff313a4a.png">

Could someone help me to fix this issue ?

**Comment by outbounder** [comment]
@dimitardanailov yeap. I've mistaken yesterday when doing the upgrade. 

This https://github.com/node-organic/organic-stack-template/blob/master/index.js#L12 should read `sourceDirs` because of breaking change to https://github.com/node-organic/organic-stack-upgrade 2.0.0

Thanks for the issue report -> I've just fixed it so it should be fine

**Comment by dimitardanailov** [comment]
@outbounder Great !!! 👏👏👏

I reviewed your pull request and now I'm familiar how to fix issues. 👊
